# Generated by Django 4.2.5 on 2023-10-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_material_producto_alter_estado_idcliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='predioP',
            new_name='precioP',
        ),
        migrations.AlterField(
            model_name='material',
            name='precioM',
            field=models.BigIntegerField(),
        ),
    ]
