# Generated by Django 4.2.5 on 2023-11-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_encargado_usuario_estatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cantidadM',
            field=models.BigIntegerField(default=1),
        ),
    ]
