# Generated by Django 4.2.5 on 2023-11-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_material_cantidadm'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='descripcionM',
            field=models.CharField(default='hola', max_length=200),
        ),
    ]
