# Generated by Django 4.2.5 on 2023-11-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_material_descripcionm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descripcionM',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
