# Generated by Django 4.2.5 on 2023-12-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_material_descripcionm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='nombreM',
            field=models.CharField(max_length=100),
        ),
    ]
