# Generated by Django 4.2.5 on 2023-12-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_material_nombrem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descripcionM',
            field=models.CharField(default='none', max_length=300),
        ),
    ]
